FirebaseError: The query requires an index. You can create it here: https://console.firebase.google.com/v1/r/project/battlezone-faa03/firestore/indexes?create_composite=Ck5wcm9qZWN0cy9iYXR0bGV6b25lLWZhYTAzL2RhdGFiYXNlcy8oZGVmYXVsdCkvY29sbGVjdGlvbkdyb3Vwcy90ZWFtcy9pbmRleGVzL18QARoNCglsZWFkZXJVaWQQARoNCgljcmVhdGVkQXQQAhoMCghfX25hbWVfXxAC